spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 33386
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db.changelog/main-changelog.xml
    enabled: true
    default-schema: public

server:
  port: 8095

log:
  execution:
    enabled: true
